alkem-io/website

config/_default/menus.yaml
config/_default/params.yaml
content/en/about/about-foundation.md

- I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md.
https://github.com/cherrytwist/Coordination/blob/master/LICENSE.

merge develop into main

---

content/en/legal/demo/cookies.md

added cookies information

---

content/en/legal/hub/aup.md
content/en/legal/hub/cookies.md
content/en/legal/hub/hub.md
content/en/legal/hub/index.md
content/en/legal/hub/tc.md
content/en/security/index.md
content/en/security/security.md

more legal/security docs and other minor changes

---

config/_default/menus.yaml
content/en/support/support.md

updated support page

---

content/en/home/intro-cta.md

call to hub iso demo

---

content/en/home/what-can-we-do-different.md

Correct a sentence under 'what can we do different'

fix garbled sentence

---

config/_default/params.yaml
content/en/legal/hub/hub.md
content/en/legal/hub/tos-b2b.md
resources/_gen/assets/scss/scss/main.scss_9f896623db74eba16a49d52c1955683d.content

Add Terms of Sale

---

content/en/legal/hub/tos-b2b.md

To look at still:
- guarantees on continuity from other services?

updated toc for b2b to remove text re refundability; other comments.

---

assets/jsconfig.json
content/en/partners/partner-intro.md

add Essif and EU logo to partner page

---

layouts/partials/custom_head.html

add https redirect

---

layouts/partials/custom_head.html

added check for localhost

---

content/en/post/2021-09-digicampus-event/index.md

updated text

---

LICENSES.md
config/_default/config.yaml
content/en/legal/demo/aup.md
content/en/legal/demo/cookies.md
content/en/legal/demo/tc.md
content/en/legal/hub/aup.md
content/en/legal/hub/cookies.md
content/en/legal/hub/tc.md
content/en/legal/hub/tos-b2b.md
content/en/post/2021-04-sidnfonds/index.md

update foundation name

---

assets/jsconfig.json
content/en/home/banner.md
content/en/home/call-out.md
content/en/home/intro-cta.md

add banner

---

content/en/post/2022-03-uwv/index.md

add notification about article being written in Dutch

add notification about post been written in Dutch

---

assets/jsconfig.json
content/en/newsletter/newsletter.md

WIP: needs march newsletter link

added old newsletter links to newsletter page

---

layouts/partials/widgets/carousel-widget.html

Signed-off-by: Rosa Swarte <64191883+Roseghost@users.noreply.github.com>
Navigation and arrows added to carousel aswell as changes to spacing
Closes #204 

Carousel #204

---

content/en/newsletter/newsletter.md

Add april newsletter

---

config/_default/menus.yaml
config/_default/params.yaml
content/en/home/10-footer-call-out.md
content/en/home/3-carousel-widget.md
content/en/home/3-why-alkemio.md
layouts/partials/site_footer.html
layouts/partials/widgets/carousel-widget.html

Updates the footer by example of adobe (https://xd.adobe.com/view/01a4a302-15f3-48a6-a5d7-4fa505951318-54f7/) and fixes responsiveness of carousel. +some margin/padding fixes here and there
----
Currently on hold due to the footer not being full width. Seems to be auto generated by container of page-footer.
- I understand that submitting the pull …

Update of footer and homepage

---

content/en/home/3-why-alkemio.md
content/en/home/5-footer-call-out.md

Adds demo video to index
Took a while to get responsive sorry
Closes #233 

Demo video

---

config/_default/menus.yaml
content/en/releases/index.md
content/en/releases/releases.md
layouts/partials/site_footer.html

added in framework for release notifications sign up

---

layouts/partials/custom_head.html

remove Matomo

---

layouts/partials/site_footer.html

Closes #250 and file is better formatted.
Adds row and columns to make it responsive. 

Footer responsive fix

---

config/_default/menus.yaml

made manifesto visible again

---

config/_default/config.yaml
content/en/post/_index.md
layouts/partials/views/blog.html
layouts/section/post.html

Responsive! Give 2 lines of title, 2 of description and also fits 2 lines of author. Will stack under each other once the screen size becomes smaller
- I understand that submitting the pull request requires agreeing to and signing the contributor …

Blogpost layout update

---

content/en/manifesto/3-header-call-out.md

changed link

---

content/en/manifesto/3-header-call-out.md
content/en/manifesto/9-footer-call-out.md

changed header and footer link in cta of the manifesto page

changedcta

---

README.md

After the domain change readme files are broken

Fix: links in readme files [alkem-io#711]

---

assets/jsconfig.json
content/en/newsletter/newsletter.md

Added newsletter june 2022

---

config/_default/menus.yaml
content/en/faq/1-faq.md
content/en/faq/2-why-alkemio.md
content/en/faq/3-alkemio-foundation.md
content/en/faq/4-platform-usage.md
content/en/faq/index.md
layouts/partials/custom_head.html

Adding FAQ

---

layouts/partials/custom_head.html
static/css/custom.css

Makes blogpost pagina same width as rest of website. 
Also creates css file to clean up code in near future. 

Layout fix + css file created

---

data/fonts/alkemio.toml

Change the default font tp Monserat to align with hub style

Change default font to Montserrat

---

assets/jsconfig.json
config/_default/menus.yaml
content/en/news/1-news.md
content/en/news/index.md

To merge after discussion with Fintan

added news top level menu entry

---

layouts/partials/custom_head.html

Fix issue #341 
- add missing '/'
- remove redundant bootstrap code

WIP:  fix bug issue #341

---

netlify.toml

WIP: add headers section to netlify.toml

---

config/_default/params.yaml
layouts/_default/baseof.html
layouts/partials/site_footer.html

Makes footer full width. 
Adds base html to be able to adjust certain things, in this case the width of footer as it was being withheld by container. 
This file comes from the wowchemy github repo

Full width footer #340

---

.vscode/settings.json
netlify.toml

Add reporting URL to website headers.

add report-uri reporting

---

content/en/newsletter/newsletter.md

Added september newsletter

---

content/en/partners/7-supporters.md

Changed other partners to supporters and added essif lab disclaimer.

Update and rename 7-other-partners.md to 7-supporters.md

---

assets/jsconfig.json
content/en/partners/10-footer-call-out.md
content/en/partners/7-supporters.md
content/en/partners/9-become-partner.md
static/css/custom.css

Update margin on partner page as per requested by Denise & Birgit + Photo responsiveness added on lower rows. 
Cleaned up some code with classes. - Future needs more cleaning up as custom.css now works but better to open this under seperate issue when the rest is done.
- I understand that submitting the pull request requires agreeing to and signing the …

Fixed margin + logo responsive

---

content/en/contact/1-contact.md

The contact form on the site had a wrong ID

fix contact form ID

---

content/en/faq/2-why-alkemio.md
content/en/faq/4-platform-usage.md

Added one question

---

content/en/newsletter/newsletter.md

Add October Newsletter

---

content/en/releases/1-latest-release.md
content/en/releases/2-recent-releases.md

Release 2022 11 09

---

content/en/releases/1-latest-release.md
content/en/releases/2-recent-releases.md

Release 11-14

---

content/en/faq/2-why-alkemio.md
content/en/faq/4-platform-usage.md
content/en/help/2-manuals-faq-blocks.md

Added Content help page

---

content/en/privacy.md

Update privacy.md
- correct form address
- add dpo email address

update privacy.md with correct form address and add email for dpo

---

content/en/news/4-twitter-feed.md
content/en/news/5-news-tags.md

Adds Twitter feed on news page

Adds twitter feed

---

content/en/partners/10-footer-call-out.md
content/en/partners/8-quotes.md
layouts/partials/widgets/text-carousel-widget.html

Closes #394 if approved!
Excluded organization logo 

Quote carousel for partner page #394

---

content/en/help/1-title.md

From www.Alkem.io to https://alkem.io/

Update link in intro text

---

static/.well-known/security.txt

RFC 9116
A File Format to Aid in Security Vulnerability Disclosure
[Abstract](https://www.rfc-editor.org/rfc/rfc9116#abstract)
When security vulnerabilities are discovered by researchers, proper reporting channels are often lacking. As a result, vulnerabilities may be left unreported. This document defines a machine-parsable format ("security.txt") to help organizations describe their vulnerability disclosure practices to make it easier for researchers to report vulnerabilities.
[Status of This Memo](https://www.rfc-editor.org/rfc/rfc9116#name-status-of-this-memo)
This document is not an Internet Standards Track specification; it is published for informational purposes.
This document is a product of the Internet Engineering Task Force (IETF). It represents the consensus of the IETF …

add security.txt

---

assets/jsconfig.json
go.sum
netlify.toml

bump hugo to 0.108 and Go to 1.19

---

content/en/post/2022-12-key-concepts/index.md

removed the title

---

layouts/partials/widgets/banner-widget.html

Quick update to original visuals as per requested by Birgit
will have to be update again during verison change but quick fix for now. 

Banner update

---

layouts/partials/hooks/footer-start/custom.html

2023 footer

---

config/_default/params.yaml
layouts/partials/components/footers/alkemio-footer.html

Helps with any future adjustments of default + takes out the unwanted extra footer at the bottom of the site.

Updates footer out of default

---

content/en/post/2022-04-translation-uwv/index.md
content/en/post/2022-04-vng/index.md
content/en/post/2022-05-wisdom/index.md
content/en/post/2022-06-28-domain/index.md
content/en/post/2022-06-29-home-page/index.md
content/en/post/2022-06-30-one-year/index.md
content/en/post/2022-07-spreadsheet/index.md
content/en/post/2022-08-knowledgebase/index.md
content/en/post/2022-09-callouts/index.md
content/en/post/2022-09-ux-refresh/index.md
content/en/post/2022-12-key-concepts/index.md
content/en/post/2022-12-ui-refresh/index.md

Adding tagline header

---

content/en/home-lr/contribute/index.md

Ik heb hier me naar you veranderd

veranderingen

---

config/_default/config.yaml

Change from Alkemio to Alkemio Foundation

Website name update

---

content/en/authors/pavlic-viki/_index.md

fixed viki display name

---

content/en/releases/1-latest-release.md
content/en/releases/2-recent-releases.md

release notes added

---

content/en/help-community-management/1-introduction.md
content/en/help/2-manuals-faq-blocks.md

link fixed

---

content/en/newsletter/newsletter.md

Upload june newsletter

---

content/en/releases/1-latest-release.md
content/en/releases/2-recent-releases.md

Add release notes

---

content/en/newsletter/newsletter.md

newsletter summer

---

content/en/about-structure/2-purpose-first.md
content/en/about-structure/4-group-structure.md
content/en/about-structure/5-double-lock.md
content/en/newsletter/newsletter.md

double lock as top section

---

content/en/about-vacancy/vacancy-community-intern/2-do-good-and-gain-experience.md
content/en/about-vacancy/vacancy-community-intern/3-over-alkemio.md
content/en/about-vacancy/vacancy-community-intern/4-jouw-rol.md
content/en/about-vacancy/vacancy-community-intern/5-bottom.md

Update spelling errors vacancy

---

config/_default/menus.yaml
content/en/about-investors/2-returns.md
content/en/about-investors/3-economic-returns.md
content/en/authors/pavlic-viki/_index.md
content/en/authors/ragni-mayte/_index.md

fix menu, update team, add comment from investor re returns

---

netlify.toml

Add the rights CSP for the Netlify CMS

fix CSP's for CMS

---

netlify.toml

fix CSP's for CMS 2

---

content/en/faq/2-why-alkemio.md

faq link changes

---

content/en/faq/2-why-alkemio.md

fixed faq link

---

assets/scss/blocks/hero-custom.scss
content/en/_index.md
content/en/about-structure/10-call-out.md

Hero blocks with centered buttons.
and a couple of typos

Hero CTA text align

---

content/en/about-structure/index.md

Updated (sub)title structure page to be consistent with the other pages

---

content/en/about-governance/index.md

Update governance styling subtitle to be consistent

---

content/en/manifesto/index.md

Updated styling of the title to be consistent with other pages

---

content/en/help/index.md

Link that redirected old help center in foundation website to platform website was broken. This PR fixes it.

fixed link redirecting old help center to platform website

---

layouts/partials/blocks/newsletter.html

added most recent newsletters to foundation website

November december 2023 newsletters

---

content/en/about-investors/index.md

updated onepager for investors on Foundation website

updated onepager for investors

---

content/en/post/2021-08-problem-well-defined/index.md

formatting

---

content/en/news/7-news-blog-platform.md

show all posts on news page

---

content/en/post/2024-11-jan-intro/index.md

added another link

---

content/en/post/2024-11-jan-intro/index.md

updated title for Jan

---

netlify.toml

disable usage of robots file for production

---

content/en/about-contact/index.md

implemented changes from issue #1512

implemented changes from issue #1512

---

netlify.toml

trying to fix netlify config

---

go.mod
netlify.toml

tidy up netlify config

---

content/en/about-governance/index.md
content/en/about-investors/index.md
content/en/partners/index.md
content/en/post/2022-06-28-domain/index.md

tidy up of investor page

---

content/en/_index.md
content/en/about-contact/index.md
content/en/about-structure/index.md
content/en/partners/index.md

Deleted and/or updated dead links on the Alkemio Foundation website. 
Minor changes and updates to ensure links are active. 

Minor changes and clearing dead links.

---

content/english/_index.md

move the stewardship to be in the middle

---

hugo.toml

fix permalinks

---

themes/fortify-hugo/layouts/_default/baseof.html
themes/fortify-hugo/layouts/partials/essentials/head.html

remove gtm in prod

---

config/_default/params.toml
content/english/about/_index.md

Getting this up and running. 

---

themes/fortify-hugo/layouts/blog/single.html

Fix blog layout

---

content/english/about/_index.md
themes/fortify-hugo/layouts/about/list.html

tidy up list
